rule run_all:
     input: ['output/Luca/data.txt', 'output/Fred/data.txt', 'output/Guillaume/data.txt']

rule run_search:
     input: ['inputs/phones.txt', 'inputs/addresses.txt']
     output: 'output/{name}/data.txt'
     run:
         name = wildcards.name
         with open(str(input[0]), 'rt') as fi:
             for myline in fi:
                 if myline.find(name) != -1:
                     print(myline)
                     with open(str(output), 'wt') as output_file:
                         output_file.write(str(myline))
                         with open(str(input[1]), 'rt') as address:
                             for line in address:
                                 if line.find(name) != -1:
                                     print(line)
                                     output_file.write(str(line))