configfile: "cfg.yaml"

## Dummy rule containing only final product to make snakemake without rule label work.
rule run :
    input : ["data.txt"]

## The actual rules are in includes
include : "merge.snake"
include : "get.snake"


