name: SK Build
on: [push, pull_request]

jobs:  
  build:
     name: Set up Python 3.7
     runs-on: ubuntu-latest
     #strategy:
     #  fail-fast: true
     #  max-parallel: -1
     #  matrix:
     #    go: ["1.12.x", "1.13.x"]
     steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: | 
          source ${CONDA}/etc/profile.d/conda.sh
          conda config --add channels conda-forge
          conda env create -f environment.yml -n my-analysis-env
          conda activate my-analysis-env
          conda install --yes jupyterlab
          pip install git+https://github.com/chrisburr/recommonmark.git@patch-1
          pip install starterkit-ci>=0.0.12
      - name: Starterkit CI
        run: |
          starterkit_ci build
          starterkit_ci check
      # - name: Test
      #   run: |
      #     test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && starterkit_ci deploy
